### ISSUE TITLE
boot-digest-0.8.ebuild: Misplaced quotation mark

### ISSUE THREAD

**Issue by DuPol** [alonbl/alon-barlev-overlay#1]
Ebuild fails with:
 * ERROR: sys-apps/boot-digest-0.8::alon-barlev failed (install phase):
 *   newinitd: Need two arguments, old file and new file
 * 
 * If you need support, post the output of `emerge --info '=sys-apps/boot-digest-0.8::alon-barlev'`,
 * the complete build log and the output of `emerge -pqv '=sys-apps/boot-digest-0.8::alon-barlev'`.
 * The complete build log is located at '/var/tmp/portage/sys-apps/boot-digest-0.8/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sys-apps/boot-digest-0.8/temp/environment'.
 * Working directory: '/var/tmp/portage/sys-apps/boot-digest-0.8/work/boot-digest-boot-digest-0.8'
 * S: '/var/tmp/portage/sys-apps/boot-digest-0.8/work/boot-digest-boot-digest-0.8'

Patch:
diff --git a/sys-apps/boot-digest/boot-digest-0.8.ebuild b/sys-apps/boot-digest/boot-digest-0.8.ebuild
index bc2a98f..fdac681 100644
--- a/sys-apps/boot-digest/boot-digest-0.8.ebuild
+++ b/sys-apps/boot-digest/boot-digest-0.8.ebuild
@@ -22,7 +22,7 @@ S="${WORKDIR}/${PN}-${P}"

 src_install() {
        make install DESTDIR="${D}" || die
-       newinitd "${FILESDIR}/boot-digest-check.init boot-digest-check"
+       newinitd "${FILESDIR}"/boot-digest-check.init boot-digest-check
 }

 pkg_postinst() {

**Comment by alonbl** [comment]
Thanks!
